#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config normal_border_color '#24273a'
bspc config focused_border_color '#c6a0f6'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
spc rule -a Screenkey manage=off

# prelaunch
launchbar
picom -b
setxkbmap -layout us,ru -option grp:alt_shift_toggle
nitrogen --restore
xsetroot -cursor_name left_ptr
dunst
